package pl.dobberstudio.game;

public enum CurrentLocation {
    WORK_ROPUCH, CITY, GYM, TOAD, CHARACTER_PANEL, HOUSE, FLORIST, JEWELLER, CLOTHER, WAIFU_PANEL, RESTAURANT, CINEMA, ORLEN, PUB, PARK, ENDING_BAD, ENDING_GOOD, ENDING_BEST, SPLASH
}